name: diabetes_prediction_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - pip:
      - mlflow==2.19.0
      - dagshub
      - joblib
      - python-dotenv