name: diabet-pred-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn
      - seaborn
      - matplotlib
      - dagshub
      - joblib
      - python-dotenv