name: Diabetes Prediction CI/CD

on:
  # Trigger when there is a change or push to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Trigger manually via GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: diabet-pred-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Environment
        run: |
          python --version
          pip list

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
        working-directory: MLProject
        run: |
          mlflow run . -P data_path=diabetes_processed.csv -m rf --env-manager=local

      - name: Get Latest MLflow run_id
        working-directory: MLProject/models_tuned/
        run: |
          RUN_ID=$(cat best_tuned_model_run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      - name: Install Python Dependencies
        run: |
          pip install docker

      - name: Upload to GitHub Artifacts
        if: env.RUN_ID != ''
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-prediction-model-${{ env.RUN_ID }}
          path: MLProject/models_tuned/
          retention-days: 90

      - name: Build Docker Model
        if: env.RUN_ID != ''
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "diabetes-prediction"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag diabetes-prediction:latest ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-prediction:${{ env.RUN_ID }}
          docker tag diabetes-prediction:latest ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-prediction:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-prediction:${{ env.RUN_ID }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-prediction:latest
